@echo off
chcp 65001 >nul
echo Starting Image Perspective Correction Application...
echo 正在启动图片梯形裁剪校正应用...

REM Check if Python is installed
echo Checking Python installation...
echo 检查Python安装...
python --version >nul 2>&1
if errorlevel 1 (
    echo Error: Python not found, please install Python 3.7 or higher
    echo 错误：未找到Python，请先安装Python 3.7或更高版本
    pause
    exit /b 1
)

REM Check if virtual environment exists
echo Checking virtual environment...
echo 检查虚拟环境...
if not exist "venv\" (
    echo Creating virtual environment...
    echo 创建虚拟环境...
    python -m venv venv
)

REM Activate virtual environment
echo Activating virtual environment...
echo 激活虚拟环境...
call venv\Scripts\activate.bat

REM Install dependencies
echo Installing dependencies...
echo 安装依赖包...
pip install -r requirements.txt

REM Start application
echo Starting application server...
echo 启动应用服务器...
echo Please visit http://localhost:8000 in your browser
echo 请在浏览器中访问 http://localhost:8000
python main.py

pause
